### ISSUE TITLE
TypeError: Cannot read property 'engine' of undefined

### ISSUE THREAD

**Issue by zgj233** [semiromid/compress-images#10]
excuse me, I am a newbie and I used win10.
1. I install pngquant Binary for Windows (v2.11.7)
2. I **don't** add pngquant to PATH environment variable, but I set "bin" params in package.json, linke this:
```json
{
   "name": "my-blog-backend",
   "bin": {
         "pngquant": "D:\\chrome下载\\pngquant-windows\\pngquant\\pngquant.exe"
  },
}
```
 then used
```npm  link```

3. I refer to your code and running it

result:
```error
TypeError: Cannot read property 'engine' of undefined
```
how I could use pngquant with Node.js , thanks very much

**Comment by semiromid** [comment]
You can to see base example:
[base example](https://github.com/semiromid/compress-images/tree/master/example)

**Comment by zgj233** [comment]
@semiromid thanks，According to what you said, I succeeded.

1. InputPath must be written as  the wildcard form like ``` src/img/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif} ```,  couldn't I use a detail path like ```src/img/myDetailPath/one.png ``` ?

2. What happens when I use ```npm install ``` ?  You download real [pngquant](https://pngquant.org) lib or other real 'compress image lib'  something like jpegtran, mozjpeg, webp,svgo, imagemagick ···
If you do, how exactly do you do it, can you teach me? please.

3. When I run node compress-image.js command in your example project, img, png, gif were disposed successful. But throw error when dealing with SVG:
```powershell
exec error : Error: Command failed: svgo --multipass -i src/img/my_post_images_1/NASA_logo.svg -o build/img/my_post_images_1/NASA_logo.svg
'svgo' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by semiromid** [comment]
I updated example, check new version.
[https://github.com/semiromid/compress-images/tree/master/example](https://github.com/semiromid/compress-images/tree/master/example)
to write manual  
[https://github.com/semiromid/compress-images/blob/master/example/Manual.txt](https://github.com/semiromid/compress-images/blob/master/example/Manual.txt)

Write please if you will be get error.

1 You could use detail path like src/img/myDetailPath/one.png.

2 You download 
https://github.com/imagemin/pngquant-bin  ----> https://pngquant.org/
You no need use `npm install` - check new version example.

3.check new version example.

**Comment by semiromid** [comment]
Fix - https://github.com/semiromid/compress-images
