### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by jehadja** [semiromid/compress-images#11]
hi thanks for this great package , unfortunately  it doesn't work with me i have several  Centos servers i already try it on 3 servers have same result ` npm install ` goes well all package have green sign installed and pass the test when i run task with gulp it start normally  after period give this massage i think it mean it doesn't create output for current fille  

```
 File from: ./upload/blockmenu/ru/0_22643600_1473931384_img.jpg
 File to: ./testimg/blockmenu/ru/0_22643600_1473931384_img.jpg
 Compression algorithm: [mozjpeg]
 File was size: [41.37KB] | File have size: [19.96KB] | Compression: [51.76%]
-----------------------------------
 New directory was created: ./testimg/_source/catalog/ru/  
 New directory was created: ./testimg/_source/catalog/ru/  
 New directory was created: ./testimg/_source/catalog/ru/  
fs.js:110
    throw err;
    ^

Error: ENOENT: no such file or directory, stat './testimg/catalog/ru/0_12826300_1484311318.jpg'
    at Object.fs.statSync (fs.js:914:3)
    at getFilesizeInBytes (/var/www/vhosts/sitename.ru/httpdocs/node_modules/compress-images/index.js:1360:23)
    at /var/www/vhosts/sitename.ru/httpdocs/node_modules/compress-images/index.js:569:29
    at exithandler (child_process.js:289:5)
    at ChildProcess.errorhandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:223:12)
    at onErrorNT (internal/child_process.js:394:16)
    at process._tickCallback (internal/process/next_tick.js:174:19)
```

**Comment by semiromid** [comment]
Hello, @jehadja .
Thank you for your alert.

> i think it mean it doesn't create output for current fille

Yes, i will be watch it.
Show please you source code "compress-images".

**Comment by semiromid** [comment]
I have good work

'Starting compress images'
 New directory was created: build/testimg/_source/catalog/ru/
 New directory was created: build/testimg/_source/catalog/ru/
 New directory was created: build/testimg/_source/catalog/ru/
-----------------------------------
 File from: src/testimg/_source/catalog/ru/0_12826300_1484311318.jpg.jpg
 File to: build/testimg/_source/catalog/ru/0_12826300_1484311318.jpg.jpg
 Compression algorithm: [mozjpeg]
 File was size: [180.73KB] | File have size: [39.88KB] | Compression: [77.94%]
-----------------------------------
'Compress images completed'

**Comment by semiromid** [comment]
I have good work

```
'Starting compress images'
-----------------------------------
 File from: src/testimg/_source/catalog/ru/0_12826300_1484311318.jpg
 File to: build/testimg/_source/catalog/ru/0_12826300_1484311318.jpg
 Compression algorithm: [mozjpeg]
 File was size: [180.73KB] | File have size: [39.88KB] | Compression: [77.94%]
-----------------------------------
'Compress images completed'
'Console will be close after [20] seconds...'
```

**Comment by semiromid** [comment]
It package **bin**

**Comment by jehadja** [comment]
hi thanks a lot for trying to help me i think i found the problem . 
jpeg-recompress -- some time can't create compress file for color convert issue  exit with code 
Unsupported color conversion request
```
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'Unsupported color conversion request\n',
  failed: true,
  signal: null,

```
also guetzli have the same problem with gary colors 
exit with the following code 
Only YUV color space input jpeg is supported
Guetzli processing failed
also exist with code 1 
i think you need to add log file for files which don't go through script and then print it to use but not stop code to trough error on log or or on log file 

hope it will help you on development 👍 
and thanks again for this package

**Comment by semiromid** [comment]
@jehadja  You would could me send image which you try compresses?
[https://imgur.com/](https://imgur.com/)
I would like to reproduce the problem.
Thank you.

**Comment by semiromid** [comment]
Fix - https://github.com/semiromid/compress-images
