### ISSUE TITLE
await for compress_images

### ISSUE THREAD

**Issue by vipulsolanki8466** [semiromid/compress-images#15]
How can I use promise with compress-images? My code is something like this, This is return resolve before complete `image-compress` process.
`
	let compressImage = (UploadDir, contentType) => {
		return new Promise((resolve, reject) => {
			let INPUT_path_to_your_images = UploadDir + '*.{jpg,JPG,jpeg,JPEG,png,svg,gif}';
			let OUTPUT_path = './public/uploads/compressed/';
			if (!fs.existsSync(OUTPUT_path)) {
				fs.mkdirSync(OUTPUT_path);
			}

			compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: false, statistic: true, autoupdate: true}, false,
                {jpg: {engine: 'mozjpeg', command: ['-quality', '60']}},
                {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                {svg: {engine: 'svgo', command: '--multipass'}},
                {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}},
                function(err){
                    if(err){
                        return reject(err);
                    }
                });
            return resolve({OUTPUT_path : OUTPUT_path, msg: 'Image compression is done.'});
	    });
	};
`

**Comment by semiromid** [comment]
Hello, @vipulsolanki8466 !
Thank you for your alert.

See to - Example 2 
See to - Doc


```
callback (err, completed): returns:
   err (type:object|null)
       engine - The name of the algorithm engine
        input - The path to the input image
        output - The path to the output image
  completed (type:boolean)
      true - result completed.
      false - result do not complete.
```

**Comment by paperscissors** [comment]
For posterity, here's an example on how to leverage the callback inside of a Promise, so you can use chaining or async/await:

```
var compress_images = require('compress-images');

const compressImage = () => {
  return new Promise((resolve, reject) => {
    compress_images('src/*.{jpg,JPG,jpeg,JPEG}', 'src/output/', {
      compress_force: false,
      statistic: true,
      autoupdate: true
    }, false, {
      jpg: {
        engine: 'jpegtran',
        command: ['-trim', '-progressive', '-copy', 'none', '-optimize']
      }
    }, {
      png: {
        engine: false,
        command: false
      }
    }, {
      svg: {
        engine: false,
        command: false
      }
    }, {
      gif: {
        engine: false,
        command: false
      }
    }, function(err, completed) {

      if (err !== null) {
        reject(new Error(err));
      }
      if (completed === true) {
        console.log('completed!')
        resolve('Completed');
      }
    })
  });
}

async function doTasks () {
  console.log('output #1')
  await compressImage()
  console.log('output #2')
}

doTasks()
```

output:

```
output #1
completed!
output #2 
```

Obviously you want to be ready to handle an error.
