### ISSUE TITLE
multiple image extension not accepting for single image and callback too not working

### ISSUE THREAD

**Issue by sathish2k** [semiromid/compress-images#2]
var imagedir1=./public/uploads/b362bec6-52ce-42dc-a8a9-01a227adedd6.jpg
  compress_images(imagedir1,  './public/uploads/', {compress_force: false, statistic: true, autoupdate: true}, false,
           {jpg: {engine: 'mozjpeg', command: ['-quality', '75']}},
           {png: {engine: 'pnquant', command: false}},
           {svg: {engine: false, command: false}},
           {gif: {engine: false, command: false}},function(res){
           console.log(res) //not working
          //  fs.unlink(imagedir1);
           });

**Comment by semiromid** [comment]
1 - API don't` have property "res".


2- You turn on "**png engine**" while you use only **jpg extension**.

Try to it
```
var imagedir1=./public/uploads/b362bec6-52ce-42dc-a8a9-01a227adedd6.jpg
compress_images(imagedir1, './public/uploads/', {compress_force: false, statistic: true, autoupdate: true}, false,
{jpg: {engine: 'mozjpeg', command: ['-quality', '75']}},
{png: {engine: false, command: false}},
{svg: {engine: false, command: false}},
{gif: {engine: false, command: false}},function(res){
console.log(res) //not working
// fs.unlink(imagedir1);
});
```
