### ISSUE TITLE
completed is always false despite successfull compression

### ISSUE THREAD

**Issue by Connum** [semiromid/compress-images#25]
In the callback function, `completed` always returns `false` for me, but the compression seems to work (the compressed files are output in the correct directory) and when I turn on the `statistic` option, I can see the statistics about how much file size was saved.

**Comment by semiromid** [comment]
Hello, Connum,

Thank you very much for your work!
I did merge your the commit.

All the best,

**Comment by semiromid** [comment]
@Connum Hello,

Thank you for your alert!

`completed` returns `true` on last file. 

You sure that `completed` returns `false` on last file? 

Try to compress one file and see. Please write me the result.

```
    compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: false, statistic: true, autoupdate: true}, false,
                                                {jpg: {engine: 'mozjpeg', command: ['-quality', '60']}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                                                {svg: {engine: 'svgo', command: '--multipass'}},
                                                {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, function(error, completed, statistic){
    

                console.log('-------------');
                console.log(error);
                console.log(completed);
                console.log(statistic);
                console.log('-------------');

    });
```

**Comment by Connum** [comment]
Hmm, that's odd, even with one file, it returns `false`. But I guess as long as my files are there and there's no error, I'll be fine! ;-)

**Comment by semiromid** [comment]
Check as follows:

Find in index.js
```
1530             if(length_files === 0){
1531                 return callback(null, true);
1532             }
1533
1534             return callback(null, false);
1535        }
```

replace to

```                 console.log(length_files);
1530             if(length_files === 0){
1531                 return callback(null, true);
1532             }
1533
1534             return callback(null, false);
1535        }
```
And tell me what's going on, what is result.

**Comment by Connum** [comment]
Sorry for the delay! Now, this is quite strange... When the callback for the first compressed file is called, `length_files` starts at `-1` and decreases with every call (up to `-52` in my case).

The issue might be that I init compress-images once via
```js
const compressImages = require('compress-images');
```
and then call `compressImages(...)` in a loop due to the way my build script works. So I guess there's a shared scope accessing the same `length_files` variable as there are no instances created but rather `compressImages` works as a singleton. Still, I don't get why `length_files` would ever become smaller than 0.

**Comment by semiromid** [comment]
@Connum Thank you very much for wrote me! 

I think I fixed this problem. Please check.

**Comment by Connum** [comment]
After updating to 1.5.6, my script now crashes with the following errors:

```
D:\***\node_modules\brotli\build\encode.js:3
1<process.argv.length?process.argv[1].replace(/\\/g,"/"):"unknown-program");b.arguments=process.argv.slice(2);"undefined"!==typeof module&&(module.exports=b);process.on("uncaughtException",function(a){if(!(a instanceof y))throw a;});b.inspect=function(){return"[Emscripten Module object]"}}else if(x)b.print||(b.print=print),"undefined"!=typeof printErr&&(b.printErr=printErr),b.read="undefined"!=typeof read?read:function(){throw"no read() available (jsc?)";},b.readBinary=function(a){if("function"===

                                                                       ^

SyntaxError: Unexpected number in JSON at position 61
    at JSON.parse (<anonymous>)
    at fs.readFile (D:\***\node_modules\compress-images\lib\updater\index.js:22:23)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```
---
By the way, it seems like something went wrong when merging my pull request #28: Some strings are still unchanged, like "File was size" and "File have size". Could it be that not all changed lines were merged correctly?

**Comment by semiromid** [comment]
@Connum 

Try replace the file `/compress-images/lib/updater/cache.json`
or replace the data in the file to this: {"update":0,"notify":0,"alert":false}

It seems you have the wrong file `cache.json` or other.
JSON.parse(data) - cannot read JSON data and gives the error.



> By the way, it seems like something went wrong when merging my pull request #28: Some strings are still unchanged, like "File was size" and "File have size". Could it be that not all changed lines were merged correctly?

Yes. There was a problem in the merger process. I will check. Seems me need will be redo it.

**Comment by semiromid** [comment]
Try update version on: compress-images@1.5.7

**Comment by Connum** [comment]
Working like a charm, thanks @semiromid! 👍
