### ISSUE TITLE
false alert in statistics

### ISSUE THREAD

**Issue by Connum** [semiromid/compress-images#26]
While compressing svg files that have already been compressed manually via svgomg, with the `statistic` option turned on, I get the following alerts in the console:

```
 Compression algorithm: [svgo]
 [Alert] Your file has become more size!!!
 File was size: [3.83KB] | File have size: [3.83KB] | Compression: [+0%]
```

In my opintion, if the file size is exactly the same and hasn't really increased, there shouldn't be an alert.

**Comment by semiromid** [comment]
@Connum 
Hello, Connum,

Thank you very much for your work!
I did merge your the commit.

All the best,
