### ISSUE TITLE
use pngquant to compress png

### ISSUE THREAD

**Issue by liuliqianxiao** [semiromid/compress-images#3]
`execFile(pngquant, array, function (err) {

            if(option.statistic){
              //Block statistic
              //- - - - - - - - - - - - -  - - - - - - - - - - -
              //Узнаем размер файла после сжатия
              size_output = getFilesizeInBytes(output);
              
              //Находим на сколько процентов удалось сжать файл
              percent = size_output / size_in;
              percent = percent * 100;
              percent = 100 - percent;
              percent = Math.round(percent * 100) / 100;

              return callback(size_in, size_output, percent);  
              //- - - - - - - - - - - - -  - - - - - - - - - - -
            }
        }); `

This code in index.js file may throw an errs, because the param of --quality min-max.
If conversion results in quality below the min quality the image won't be saved ,so when I set statistic == true ,the function getFilesizeInBytes(output) may throw an err, because there is no output file can be found.

**Comment by semiromid** [comment]
Thanks. I'll see later.

**Comment by semiromid** [comment]
`pngquan` - Quality should be in format min-max where min and max are numbers in range 0-100.
I have good work if i use - `{png: {engine: 'pngquant', command: ['--quality=0-20']}}`
But i have done:
```
            if(null == err){
              if(option.statistic){
                //Block statistic
                //- - - - - - - - - - - - -  - - - - - - - - - - -
                //Узнаем размер файла после сжатия
                size_output = getFilesizeInBytes(output);
                
                //Находим на сколько процентов удалось сжать файл
                percent = size_output / size_in;
                percent = percent * 100;
                percent = 100 - percent;
                percent = Math.round(percent * 100) / 100;

                return callback(size_in, size_output, percent, null);  
                //- - - - - - - - - - - - -  - - - - - - - - - - -
              }
            }else{
              return callback(null, null, null, err);
            }
```
