### ISSUE TITLE
Pathing when using libray within electron application

### ISSUE THREAD

**Issue by michaeltrim** [semiromid/compress-images#30]
Hi when I use this library within an electron application I have to provide a path relative to the application source, when I would like to provide an absolute path, that can use cross platform locations.

For example:

`INPUT_PATH = `${os.homedir()}/MyAppSpecificPath/**/*.{png,jpg,svg}``

returns a Directory is empty! error from Line 243 index.js

`INPUT_PATH =  `../../../MyAppSpecificPath/**/*.{png,jpg,svg}``

(which is the correct number of directories up I need to go up to reach that path, works as expected)

`OUTPUT_PATH = `${os.homedir()}/MyAppSpecificPath/build/``

Using the absolute path for OUTPUT works fine

**Comment by semiromid** [comment]
Hello, @michaeltrim ,

Thank you for the alert!

**glob** do not can find file.

It is related with the library [glob](https://www.npmjs.com/package/glob)

__________________________

**compress-images** has option for the library **glob**

> globoption (type:boolean|other): Options module`s glob. Also you can set false;

________________________

You need to look:

[node-glob](https://github.com/isaacs/node-glob#readme)

> Options
> > absolute Set to true to always receive absolute paths for matched files. Unlike realpath, this also affects the values returned in the match event.

Write please me if you will get any result.

**Comment by michaeltrim** [comment]
Thank you, in the end I fixed using the following...

INPUT_PATH = '/MyAppSpecificPath/**/*.{png,jpg,svg}'

glob options
{root:os.homedir(), absolute: true}

**Comment by michaeltrim** [comment]
Acutally this broke the output on windows

the line

path_out_new = files[i].replace(new RegExp(path_in_part, "g"), output);

now fails as the path in file[i] contains backslashes but the path_in_part contains forward slashes

**Comment by michaeltrim** [comment]
Patched for windows by adding the following in my local node_modules folder

files[i] = files[i].replace(new RegExp("\\\\", "g"), "/");
path_out_new = files[i].replace(new RegExp(path_in_part, "g"), output);
