### ISSUE TITLE
compress-Images not getting installed on linux server

### ISSUE THREAD

**Issue by Ankit971964** [semiromid/compress-images#31]
npm i -g compress-ima
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com
/gulpjs/gulp-util-ca3b1f9f9ac5

> cwebp-bin@5.1.0 postinstall /usr/lib/node_modules/compress-images/node_modules/cwebp-bin
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/compress-images/node_modules/cwebp-bin/vendor'
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✖ Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/compress-images/node_modules/cwebp-bin/8dc9f2aa-ab97-4
16e-8b45-8bfa0ec8c89e'

> giflossy@3.0.41 postinstall /usr/lib/node_modules/compress-images/node_modules/giflossy
> node lib/install.js

  ⚠ EACCES: permission denied, mkdir '/usr/lib/node_modules/compress-images/node_modules/giflossy/vendor'
  ⚠ giflossy pre-build test failed
  ℹ compiling from source
/usr/lib/node_modules/compress-images/node_modules/onetime/index.js:15
                                throw new Error(fnName + ' can only be called once.');
                                ^

Error: callback() can only be called once.
    at onetime (/usr/lib/node_modules/compress-images/node_modules/onetime/index.js:15:11)
    at /usr/lib/node_modules/compress-images/node_modules/giflossy/node_modules/download/index.js:156:5
    at ConcatStream.<anonymous> (/usr/lib/node_modules/compress-images/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:203:15)
    at finishMaybe (/usr/lib/node_modules/compress-images/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/usr/lib/node_modules/compress-images/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at ConcatStream.Writable.end (/usr/lib/node_modules/compress-images/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DuplexWrapper.onend (/usr/lib/node_modules/compress-images/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:286:20)
    at DuplexWrapper.emit (events.js:203:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! giflossy@3.0.41 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the giflossy@3.0.41 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-07T12_25_44_410Z-debug.log

**Comment by mhstoller** [comment]
Had the same issue. Ran the installation using "sudo npm i compress-images --save --unsafe-perm=true --allow-root" and it worked. 7 vulnerabilities with this package though...

**Comment by rlaurente** [comment]
> Had the same issue. Ran the installation using
> 
> `sudo npm i compress-images --save --unsafe-perm=true --allow-root`
> 
> and it worked. 7 vulnerabilities with this package though...

I tried this but still have error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jpegoptim-bin@5.1.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jpegoptim-bin@5.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by semiromid** [comment]
> > Had the same issue. Ran the installation using
> > `sudo npm i compress-images --save --unsafe-perm=true --allow-root`
> > and it worked. 7 vulnerabilities with this package though...
> 
> I tried this but still have error
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! jpegoptim-bin@5.1.0 postinstall: `node lib/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the jpegoptim-bin@5.1.0 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Try install separately **jpegoptim-bin**
https://www.npmjs.com/package/jpegoptim-bin

**Comment by semiromid** [comment]
This problem is rescheduled
https://github.com/semiromid/compress-images/issues/21
