### ISSUE TITLE
Installing compress-images on Windows 7

### ISSUE THREAD

**Issue by buglessir** [semiromid/compress-images#34]
I'm trying to install this package on my computer, but I've a lot of errors

OS Windows 7

Node LTS 10.16.3

NPM 6.9.0

check this screenshot :

![error](https://user-images.githubusercontent.com/23656061/66267417-682dec80-e83d-11e9-8e84-2993582eec8c.jpg)

**Comment by semiromid** [comment]
Try 
`sudo npm i compress-images --save --unsafe-perm=true --allow-root`

or

Try install separately jpegoptim-bin
https://www.npmjs.com/package/jpegoptim-bin

**Comment by buglessir** [comment]
> 
> 
> @buglessir
> Try
> `sudo npm i compress-images --save --unsafe-perm=true --allow-root`
> 
> or
> 
> Try install separately jpegoptim-bin
> https://www.npmjs.com/package/jpegoptim-bin

but I'm using Windows and not Ubuntu or other Linux distributions ...

**Comment by semiromid** [comment]
@buglessir

For Windows:

`npm i compress-images --save --unsafe-perm=true --allow-root`

**Comment by semiromid** [comment]
This problem is rescheduled
https://github.com/semiromid/compress-images/issues/21
