### ISSUE TITLE
Error: Command failed: /bin/sh -c make install

### ISSUE THREAD

**Issue by 1vipulp** [semiromid/compress-images#36]
I am using this npm in my windows 10 system, it is running in local perfectly. 
On my server, there is Ubuntu 18.04, I am unable to install this package. As it ends with below mentioned error. Do you have any idea ?

Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c make install
/bin/sh: 1: make: not found

**Comment by semiromid** [comment]
Hello @1vipulp 

I found a critical error on version 1.5.8. I fixed it. Check new version 1.6.0. But i not think than it related, but you checking.
