### ISSUE TITLE
exec error 1 : Error: Command failed: npm outdated -json --long

### ISSUE THREAD

**Issue by npoliquin** [semiromid/compress-images#46]
Hey, just installed the package and run it.

The compression was good, but I have this error at the end:

`exec error 1 : Error: Command failed: npm outdated -json --long`.

Any ideas?

I copied this setup: https://github.com/semiromid/compress-images/blob/master/example/compress_images.js

**Comment by semiromid** [comment]
@npoliquin 
Hey!

I knowed about this error. This error does not affect image compression. This error related to the auto-update of this program

**Comment by npoliquin** [comment]
@semiromid Alight. Thanks! :)

**Comment by semiromid** [comment]
@npoliquin 
You are welcome! )

Download latest version.

**Comment by npoliquin** [comment]
I got this error when I tried to run the script.

`node_modules\compress-images\index.js:483
          return callback(error, completed, statistic);`
`TypeError: callback is not a function`
