### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by npoliquin** [semiromid/compress-images#47]
Some dependencies have vulnerabilities.

` High            Prototype Pollution

  Package         dot-prop

  Patched in      >=5.1.1

  Dependency of   compress-images [dev]

  Path            compress-images > npm > update-notifier > configstore >
                  dot-prop

  More info       https://npmjs.com/advisories/1213`

**Comment by semiromid** [comment]
@npoliquin 

This related with this package `npm`.

Maybe this will help you:
https://stackoverflow.com/questions/63171516/facing-vulnerability-security-issue-for-dot-prop-when-updating-to-latest-npm-pac
