### ISSUE TITLE
[FR] Allow to cache already compressed images.

### ISSUE THREAD

**Issue by vandres** [semiromid/compress-images#48]
## Background
I created a little workflow with your tool, where our DEVs copy images first in am `uncompressed` folder and have to run the command to compress and copy the files to the final folder. That is rather a tedious job, as it is not as easy as just copy the file directly into the folder.

Now I came up with the idea, that the compression could be done in the final folder already. We could then include this step just in our release. But then we would need to take care, that no double compression is done. 

Including the compression of all images, in each release, is no option, as it would take way too long.

## Feature Request
For gulp as an example, there is a plugin gulp-cache. It just creates a file which keeps an index of all already cached images. So there would be no double compression. I would wish for a similar (optional) approach for your tool too :)

**Comment by semiromid** [comment]
@vandres 

Hello!

I think it is possible that the cache is not needed. I don’t know exactly what you need, but maybe this solution will be the best for you.

Compressing an image in the same folder (this as example):
https://github.com/semiromid/compress-images

```
    const 
    compress_images = require('compress-images'),
    fs = require('fs'),
    INPUT_path_to_your_images = 'src/img/**/!(*-min).png',  // You can rewrite on 'build/img/**/!(*-min).png'
    OUTPUT_path = 'src/img/';  // You can rewrite on 'build/img/'
    
    compress_images(INPUT_path_to_your_images, OUTPUT_path, {compress_force: true, statistic: false, autoupdate: true}, false,
                                                {jpg: {engine: false, command: false}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50', '--ext=-min.png', '--force']}},
                                                {svg: {engine: false, command: false}},
                                                {gif: {engine: false, command: false}}, function(err, completed, statistic){
        if(err === null){
            fs.unlink(statistic.input, (err) => {
                if (err) throw err;
                console.log('successfully compressed and deleted '+statistic.input);
            });
        }
    });
```
