### ISSUE TITLE
svgo not working

### ISSUE THREAD

**Issue by greeto** [semiromid/compress-images#5]
svgo should use -f (source folder) and -o (output folder)

**Comment by semiromid** [comment]
Hello, Greeto!

It is command for **folder** with **SVG** files, but not for SVG files - `-f FOLDER, --folder=FOLDER : Input folder, optimize and rewrite all *.svg files`

But we can use - `-i INPUT, --input=INPUT : Input file, "-" for STDIN` and 
`-o OUTPUT`
I have works well and without these commands `-o OUTPUT` and `-i INPUT`.  

But i added fix.
Thanks you for alert!
