### ISSUE TITLE
GIF-LIB error: Image EOF detected before image complete.

### ISSUE THREAD

**Issue by SergioMatheus** [semiromid/compress-images#52]
**hey man, can u just updated into lib/webp/linux for libwebp-1.1.0-rc2-linux-x86-64.tar.gz ? just download here http://downloads.webmproject.org/releases/webp/index.html**

**this current architecture x32 is not working between the two architectures and is causing this title error**

**Comment by SergioMatheus** [comment]
#53

**Comment by semiromid** [comment]
@SergioMatheus 

Hi, Sergio!

Thank you for your alert. 

Can you download this library and check it?
[https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-linux-x86-64.tar.gz
](https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.1.0-linux-x86-64.tar.gz)

I want to notice that I saw your pull request.
I just want to add binaries myself. But I will approve your pull request.

**Comment by SergioMatheus** [comment]
this library is also working, I tested it and so far everything without a problem

**Comment by semiromid** [comment]
@SergioMatheus

Thank you very much for your alert and work.

Have a nice day and good work.
