### ISSUE TITLE
Does it protect itself from zip bombs ?

### ISSUE THREAD

**Issue by bacloud14** [semiromid/compress-images#58]
I really don't know anything about image extensions and encoding/compression. 

But I believe some extensions are a form of compress, and when there is compression, there is potential attack of compression algorithm.

**Comment by semiromid** [comment]
Hi @bacloud14 !

I have not tested. It is better to do the security separately.

**Comment by bacloud14** [comment]
Ok I'll invest some time for this. 
Thanks
