### ISSUE TITLE
Is it possible to resize ?

### ISSUE THREAD

**Issue by bacloud14** [semiromid/compress-images#59]
### Context
I have a very limited memory environment, and I don't want to implement at least for now any third party storage for my images.
I am trying to compress as much as possible. For this, I am limiting uploads to 2 MB which seems very limited as I accept captures from modern smartphones. As a result, I want to raise the limit to say 4 MB, but instantly compress as much as possible.

### Resize
I want to resize images and keep ration, say limit to 512px for width and let length relate to that keeping ratio

There are some solution like [Sharp](https://www.npmjs.com/package/sharp)

However I am afraid to do it badly, like resize after compression or before ?! also I'm afraid about extensions as I don't know much (and I want to accept most image extensions).

Any guidelines ?

Thanks a lot !

**Comment by bacloud14** [comment]
Just for illustration about where am I, this seems to work perfect with many extensions.

```
const inputPathImages = 'uploads/*.{jpg,JPG,jpeg,JPEG,png,PNG,svg,gif}';
const inputPath = 'uploads/';
const outputPath = 'public/images/';

const watcher = chokidar.watch(inputPath, {persistent: true});

watcher
    .on('add', function(path) {
      console.log('File', path, 'has been added');
      compressImages(
          inputPathImages,
          outputPath,
          {compress_force: false, statistic: true, autoupdate: true},
          false,
          {jpg: {engine: 'mozjpeg', command: ['-quality', '60']}},
          {png: {engine: 'pngquant', command: ['--quality=20-50', '-o']}},
          {svg: {engine: 'svgo', command: '--multipass'}},
          {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}},
          function(error, completed, statistic) {
            console.log('-------------');
            console.log(error);
            console.log(completed);
            console.log(statistic);
            console.log('-------------');
            // CLEAN FOLDER.
            if (error === null) {
              fs.unlink(statistic.input, (err) => {
                if (err) throw err;
                console.log('successfully compressed and deleted ' + statistic.input);
              });
            }
          },
      );
    })
    .on('change', function(path) {
      console.log('File', path, 'has been changed');
    })
    .on('unlink', function(path) {
      console.log('File', path, 'has been removed');
    })
    .on('error', function(error) {
      console.error('Error happened', error);
    });
```

**Comment by semiromid** [comment]
Hello @bacloud14 ! 

Thank you for your question.

Maybe you will be interested

[https://imageoptim.com/api/start](https://imageoptim.com/api/start)

**Comment by bacloud14** [comment]
thanks a lot !
