### ISSUE TITLE
file does not exist when it does?

### ISSUE THREAD

**Issue by ryantupo** [semiromid/compress-images#61]
crawler/screenshots/19-07-2021/expedia.com-desktop.jpeg
crawler/screenshots/19-07-2021/
   File does not exist!    

when i run my screenshot code and then the compress i get it to print the 

  const INPUT_path_to_your_images = `crawler/${partialPath.replace('../', '')}-desktop.jpeg`;
  const OUTPUT_path = `crawler/screenshots/${date}/`;

and 

crawler/screenshots/19-07-2021/expedia.com-desktop.jpeg
crawler/screenshots/19-07-2021/

this gets printed out for them both which i can click and follow and they take me to the image and the folder its meant to be in but is erroring saying file doesnt exist??? does the compressing need a delay or something maybe the file is being saved and the code trys too fast to compress and doesnt find it in time?? any help would be great

**Comment by semiromid** [comment]
Hi @ryantupo !)

Thank you for your question.)

Show your config compress images.
