### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by ronaldlong46** [semiromid/compress-images#7]
Really strange, it's working fine on my localhost. When moving to production I am now getting this error when trying to compress:

```
binding.stat(pathModule._makeLong(path), statValues);
          ^

0|app      | Error: ENOENT: no such file or directory, stat 'public/compressed/image-1517857639606.jpg'
0|app      |     at Error (native)
0|app      |     at Object.fs.statSync (fs.js:1009:11)
0|app      |     at getFilesizeInBytes (/home/bud/node_modules/compress-images/index.js:1360:23)
0|app      |     at /home/bud/node_modules/compress-images/index.js:569:29
0|app      |     at exithandler (child_process.js:206:5)
0|app      |     at ChildProcess.errorhandler (child_process.js:218:5)
0|app      |     at emitOne (events.js:96:13)
0|app      |     at ChildProcess.emit (events.js:188:7)
0|app      |     at Process.ChildProcess._handle.onexit (internal/child_process.                                                                                                                     js:217:12)
0|app      |     at onErrorNT (internal/child_process.js:376:16)
0|app      |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
0|app      |     at process._tickDomainCallback (internal/process/next_tick.js:1                                                                                                                     28:9)
0|app      | (node:2103) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using                                                                                                                      `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.                                                                                                                     html#use-mongo-client
```

This is my setup: 
```
// Image Compression
function rszImg(){
    compress_images('public/uploads/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}', 'public/', {compress_force: false, statistic: true, autoupdate: true}, false,
                                                {jpg: {engine: 'mozjpeg', command: ['-quality', '40']}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                                                {svg: {engine: 'svgo', command: '--multipass'}},
                                                {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, function(){
    });
}
```

Both my localhost and production server are running Node -v 8.9.4

**Comment by semiromid** [comment]
Hello, Ronaldlong46.
Thank you for your message.


Is there a file in this directory?
`'public/compressed/image-1517857639606.jpg'`


I understand that compression does not happen. And because of what the function `getFilesizeInBytes` 
can not find the path to the compressed image and an error occurs.


Maybe need set `./`
 `'./public/uploads/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}'` and  `'./public/'`
Still
Try specify full path to one image or specify one extension `'src/img/**/*.jpg'`

Try get error log:
`
// Image Compression
function rszImg(){
    compress_images('public/uploads/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}', 'public/', {compress_force: false, statistic: true, autoupdate: true}, false,
                                                {jpg: {engine: 'mozjpeg', command: ['-quality', '40']}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                                                {svg: {engine: 'svgo', command: '--multipass'}},
                                                {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, function(err){
            if(err != null){
                 console.error(err);
            }
    });
}
`

**Comment by semiromid** [comment]
Try specify full path to one image. As example:
 `'src/img/test.jpg' or 'src/img/'`

**Comment by semiromid** [comment]
Try remove `public` from path.


```
public --|
              | -- uploads/
              | -- build/img/
```

function rszImg(){
    compress_images('uploads/**/*.{jpg,JPG,jpeg,JPEG,png,svg,gif}', 'build/img/', {compress_force: false, statistic: true, autoupdate: true}, false,
                                                {jpg: {engine: 'mozjpeg', command: ['-quality', '40']}},
                                                {png: {engine: 'pngquant', command: ['--quality=20-50']}},
                                                {svg: {engine: 'svgo', command: '--multipass'}},
                                                {gif: {engine: 'gifsicle', command: ['--colors', '64', '--use-col=web']}}, function(){
    });
}

**Comment by ronaldlong46** [comment]
Thank you. I fixed the issue. I tried the above but it did not fixed my problem. The fix that worked was: "npm uninstall compress-images" and when it finished I ran "npm install compress-images". I think that the "mozjpeg" engine didn't install correctly. That's just a guess though. 

Thank you for creating this package it is awesome! Much easier to setup/install than the other solutions out there.

**Comment by semiromid** [comment]
> Btw, thank you for creating this package it is awesome!

Thank You! )

> The only issue I am having now is when running the compression function "rszImg()" in my case, I am using it in combination with multer, so like this "rszImg(req.file.path)", it compresses all files in my "public/uploads" folder, not just the single uploaded image I am trying to compress.

I'll check as soon as I can

**Comment by semiromid** [comment]
> Thank you. I fixed the issue. I tried the above but it did not fixed my problem. The fix that worked was a reinstall. I did "npm uninstall compress-images" and when it finished I ran "npm install compress-images". I think that the "mozjpeg" engine didn't install correctly. That's just a guess though.
> 
> The only issue I am having now is when running the compression function "rszImg()" in my case, I am using it in combination with multer, so like this "rszImg(req.file.path)", it compresses all files in my "public/uploads" folder, not just the single uploaded image I am trying to compress.
> 
> Btw, thank you for creating this package it is awesome!


I tested compress single file, in my case turned out compressed only single file and other files don't compressed.

```
    compress_images('src/source/1.jpg', 'build/', {compress_force: false, statistic: true, autoupdate: true}, false,
                                                {jpg: {engine: 'mozjpeg', command: ['-quality', '60']}},
                                                {png: {engine: false, command: ['--quality=20-50']}},
                                                {svg: {engine: false, command: '--multipass'}},
                                                {gif: {engine: false, command: ['--colors', '64', '--use-col=web']}}, function(){
    });

```
