### ISSUE TITLE
Grunt contrib

### ISSUE THREAD

**Issue by general03** [semiromid/compress-images#8]
Hello,

I would like to know if you have or to consider contrib for grunt usage ?

thx

**Comment by semiromid** [comment]
Do you want to write example how use it package with "Grunt"?

**Comment by semiromid** [comment]
Do you want to write example how use it package with "Grunt"?

**Comment by general03** [comment]
You can find my Grunt file on my repo where I need your package : https://github.com/itarverne/generator-itarverne-landing-page/blob/master/public/Gruntfile.js
thx

**Comment by semiromid** [comment]
It don't need. 
Thank you for your offer.

**Comment by general03** [comment]
So I developed one, available on https://www.npmjs.com/package/grunt-compress-images

**Comment by coldtelling** [comment]
@semiromid @general03 Just read this and I'm fucking laughing so hard, wtf ??? hahaha

What's wrong with adding a grunt build for your project @semiromid ? wtfff
Thanks @general03
